### ISSUE TITLE
Anki 2.1.39beta 1 shows this will need an update for future versions

### ISSUE THREAD

**Issue by AnKingMed** [yukach/anki21-addon-customize-sidebar#10]
It looks like the sidebar code has been moved from from browser.py into sidebar.py so this add-on will need an update. Just an FYI so you have a heads up before its public. More than happy to test things for you if needed

```
When loading '⁨Customize Sidebar⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 211, in loadAddons
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1988760596/__init__.py", line 5, in <module>
    from . import customize_sidebar
  File "/Users/Nick/Library/Application Support/Anki2/addons21/1988760596/customize_sidebar.py", line 102, in <module>
    Browser._stdTree = wrap(Browser._stdTree, custom_stdTree_since_2_1_17)
AttributeError: type object 'Browser' has no attribute '_stdTree'
```

**Comment by yukach** [comment]
thanks. I will fix it asap.

**Comment by yukach** [comment]
I fixed it but my fixes are not valid for version 2.1.40 and I decided not to merge them. I didn't test the plugin with v2.1.39. The plugin works well with v2.1.40.

**Comment by AnKingMed** [comment]
It appears this is very broken with 2.1.41, but they incorporated most of this add-on in so I would recommend just setting it on ankiweb so that it is only useable for 2.1.39 and earlier.  :)
